module PositionConstants
  POSITIONS = [
    :president_current,
    :president_fall,
    :president_spring,
    :vice_president,
    :treasurer,
    :secretary,
    :house_manager_current,
    :house_manager_fall,
    :house_manager_spring,
    :kitchen_manager_current,
    :kitchen_manager_fall,
    :kitchen_manager_spring,
    :social_chairman_current,
    :social_chairman_fall,
    :social_chairman_spring,
    :rush_chairman_current,
    :rush_chairman_fall,
    :rush_chairman_spring,
    :pledge_trainer,
    :brotherhood_chairman,
    :academic_chairman,
    :athletic_chairman,
    :alumni_relations_chairman,
    :community_relations_chairman,
    :historian,
    :fraternity_representative,
    :society_representative,
    :critic,
    :literary_chairman,
    :house_job_checker
  ]

  POSITION_NAMES = {
    president_current: "President: Current",
    president_fall: "President: Fall",
    president_spring: "President: Spring",
    vice_president: "Vice President",
    treasurer: "Treasurer",
    secretary: "Secretary",
    house_manager_current: "House Manager: Current",
    house_manager_fall: "House Manager: Fall",
    house_manager_spring: "House Manager: Spring",
    kitchen_manager_current: "Kitchen Manager: Current",
    kitchen_manager_fall: "Kitchen Manager: Fall",
    kitchen_manager_spring: "Kitchen Manager: Spring",
    social_chairman_current: "Social Chairman: Current",
    social_chairman_fall: "Social Chairman: Fall",
    social_chairman_spring: "Social Chairman: Spring",
    rush_chairman_current: "Rush Chairman: Current",
    rush_chairman_fall: "Rush Chairman: Fall",
    rush_chairman_spring: "Rush Chairman: Spring",
    pledge_trainer: "Pledge Trainer",
    brotherhood_chairman: "Brotherhood Chairman",
    academic_chairman: "Academic Chairman",
    athletic_chairman: "Athletic Chairman",
    alumni_relations_chairman: "Alumni Relations Chairman",
    community_relations_chairman: "Community Relations Chairman",
    historian: "Historian",
    fraternity_representative: "Fraternity Representative",
    society_representative: "Society Representative",
    critic: "Critic",
    literary_chairman: "Literary Chairman",
    house_job_checker: "House Job Checker"
  }
end