source 'https://rubygems.org'

gem 'rails', '4.1.8'
gem 'pg'
gem 'sass-rails', '~> 5.0.1'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',           group: :doc
gem 'spring',                     group: :development
gem 'rails_admin'
gem 'foundation-rails'
gem 'rails_serve_static_assets'
gem 'unicorn'
gem 'cancan'
gem 'rack-mini-profiler'
gem 'resque'
gem 'resque_mailer'
gem 'resque-scheduler'
gem 'paperclip'
gem 'remotipart'
gem 'aws-sdk-v1'
gem 'aasm'
gem "haml-rails", "~> 0.9"
gem 'postmark-rails'
gem 'pdfkit'
gem 'combine_pdf'
